name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 17 (required for the Android SDK)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'  # Use JDK 17 for compatibility with Android SDK tools
          distribution: 'temurin'
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true

      # Step 3: Set up Android SDK (make sure sdk-version input is removed)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      # Step 4: Ensure gradlew has execute permissions
      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      # Step 5: Install dependencies and build the project
      - name: Install dependencies and build the project
        run: |
          ./gradlew clean --info  # This will provide more detailed log output
          ./gradlew build --info

      # Step 6: Build APK file (Release)
      - name: Build APK (Release)
        run: ./gradlew assembleRelease --info

      # Step 7: Upload APK to GitHub Release
      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  serve:
    runs-on: ubuntu-latest

    steps:
      # Step 8: Get latest release version and date
      - name: Fetch latest release details
        run: |
          latest_release=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          latest_version=$(echo $latest_release | jq -r '.tag_name')
          release_date=$(echo $latest_release | jq -r '.published_at')
          echo "Latest version: $latest_version"
          echo "Release date: $release_date"

      # Step 9: Generate JSON response with version and release date
      - name: Generate JSON response
        run: |
          echo "{\"version\": \"$latest_version\", \"release_date\": \"$release_date\"}" > latest_release.json

      # Step 10: Upload generated JSON file to GitHub as an artifact
      - name: Upload release metadata
        uses: actions/upload-artifact@v2
        with:
          name: latest_release
          path: latest_release.json
