name: Build and Release APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (use JDK 11 to avoid compatibility issues with Hilt/Dagger)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
          check-latest: false

      # Step 3: Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: '30.0.3'  # Specify the Android SDK version

      # Step 4: Set execute permissions for gradlew
      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      # Step 5: Install dependencies and build the project
      - name: Install dependencies and build the project
        run: |
          ./gradlew clean --stacktrace
          ./gradlew build --stacktrace

      # Step 6: Build APK (Release)
      - name: Build APK (Release)
        run: ./gradlew assembleRelease --stacktrace

      # Step 7: Upload APK to GitHub Release
      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  serve:
    runs-on: ubuntu-latest
    
    steps:
      # Step 8: Fetch latest release details
      - name: Fetch latest release details
        run: |
          latest_release=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest")
          latest_version=$(echo $latest_release | jq -r '.tag_name')
          release_date=$(echo $latest_release | jq -r '.published_at')
          echo "Latest version: $latest_version"
          echo "Release date: $release_date"

      # Step 9: Generate JSON response
      - name: Generate JSON response
        run: |
          echo "{\"version\": \"$latest_version\", \"release_date\": \"$release_date\"}" > latest_release.json

      # Step 10: Upload generated JSON file as artifact 
      - name: Upload release metadata
        uses: actions/upload-artifact@v2
        with:
          name: latest_release
          path: latest_release.json
